package com.demo.urlshortner.repository;

import com.demo.urlshortner.model.UrlMapping;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

import java.util.List;
import java.util.Optional;

/**
 * This class represents UrlMappingRepository interface.
 */
@Repository
public interface UrlMappingRepository extends JpaRepository<UrlMapping, Integer> {

  /**
   * This method will return original url from shorturl.
   *
   * @param shortUrl shortUrl to get the original url.
   * @return original url
   */
  Optional<String> findByShortUrl(String shortUrl);


  /**
   * This method returns all short urls generated by the given user.
   *
   * @param userId id of the user.
   * @return list of urls generated by the user with userId.
   */
  List<UrlMapping> findByUserId(Long userId);
}
